name: Snyk Vulnerability Scan

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-21@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}