name: Snyk Vulnerability Scan

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  snyk:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Snyk Scan
      uses: snyk/actions/maven@v3
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: test